export type TravelMode = 'SEARCH' | 'DISCOVER';
export type CarPreference = 'NO' | 'YES' | 'IF_WORTH_IT';
export type DataStatus = 'LIVE' | 'RECENT' | 'ESTIMATED' | 'MOCK' | 'UNAVAILABLE';
export interface TravelQuery { mode: TravelMode; availabilityStart: string; availabilityEnd: string; minDays: number; idealDays?: number; maxDays: number; travellers: number; rooms: number; origin?: string; origins: string[]; budgetPerPerson?: number; region?: string; excludedDestinations?: string[]; interests?: string[]; car: CarPreference; pace?: 'RELAXED' | 'BALANCED' | 'FAST'; directPreferred?: boolean; maxStops?: number; baggage?: 'BACKPACK' | 'CABIN' | 'CHECKED'; minHotelRating?: number; freeCancellation?: boolean; flightPreference?: { allowOpenJaw: boolean; allowMultiCity: boolean; maxStops?: number; preferDirect?: boolean; }; }
export interface SourceRecord { provider: string; retrievedAt?: string; status: DataStatus; confidence: number; }
export interface PricePart { amountPerPerson?: number; groupAmount?: number; currency: 'EUR'; status: DataStatus; provider: string; retrievedAt?: string; note?: string; }
export interface TripCostBreakdown { flights: PricePart; accommodation: PricePart; transport: PricePart; access: PricePart; knownTotal?: number; knownPerPerson?: number; currency: 'EUR'; }
export interface DateCombination { departureDate: string; returnDate: string; nights: number; calendarDays: number; }
export interface Airport { iata: string; icao?: string; name: string; municipality?: string; country?: string; countryCode?: string; latitude?: number; longitude?: number; timezone?: string; }
export interface Destination { id: string; airportCode: string; airportName?: string; city: string; country?: string; countryCode?: string; latitude?: number; longitude?: number; timezone?: string; bookingCityId?: number; airport?: Airport; travelRegion?: string; }
export interface BookingLink { label: string; url: string; provider: string; }
export interface TripCandidate extends SourceRecord { id: string; destination: Destination; origin: string; dates: DateCombination; travellers: number; rooms: number; type: 'CITY' | 'NATURE' | 'ROADTRIP' | 'MULTI_STOP'; title: string; cost: TripCostBreakdown; score: number; rationale: string[]; stops?: number; flight: import('./flight.js').FlightItinerary; roadtrip?: RoadtripPlan; hotel?: { id: string; name: string; type?: string; reviewScore?: number; totalStayPrice?: number; pricePerNight?: number; currency: 'EUR'; status: DataStatus; provider: string; retrievedAt?: string; bookingUrl?: string; cancellation?: string; }; bookingLinks: BookingLink[]; }
export interface RouteLeg { from: Destination; to: Destination; distanceKm: number; durationMinutes: number; }
export interface RoadtripStop { destination: Destination; nights: number; arrivalDay: number; departureDay: number; reason?: string; }
export interface RoadtripPlan { id: string; start: Destination; end: Destination; stops: RoadtripStop[]; route: { distanceKm: number; durationMinutes: number; legs: RouteLeg[]; geometry?: [number, number][]; provider: string; status: DataStatus; retrievedAt?: string }; car?: { id: string; name?: string; supplier?: string; pickup: string; dropoff: string; groupAmount?: number; oneWayFee?: number; status: DataStatus; provider: string; retrievedAt?: string; bookingUrl?: string }; fuel: PricePart; crossBorder: boolean; crossBorderPermission: 'UNKNOWN' | 'ALLOWED' | 'RESTRICTED'; score: number; rationale: string[]; }
export type TripVariant = TripCandidate & { roadtrip?: RoadtripPlan };
