import type { FlightDiscoveryProvider } from '../../../application/providers.js';
import type { FlightItinerary, FlightSearchRequest } from '../../../domain/flight.js';
import type { TravelQuery } from '../../../domain/travel-query.js';
type ApiTicket = { origin?: string; destination?: string; origin_airport?: string; destination_airport?: string; price?: number; departure_at?: string; return_at?: string; duration?: number; transfers?: number; number_of_changes?: number; found_at?: string; link?: string; };
type ApiResponse = { success?: boolean; data?: ApiTicket[]; error?: string; };
/** Travelpayouts Data API: observed fares, deliberately never LIVE. */
export class AviasalesFlightProvider implements FlightDiscoveryProvider {
  readonly name = 'Aviasales Data'; readonly available: boolean;
  readonly capabilities = { indicative: true, live: false, oneWay: true, roundTrip: true, openJaw: false, multiCity: false, flexibleDates: true } as const;
  private readonly cache = new Map<string, { expires: number; value: FlightItinerary[] }>();
  constructor(private readonly token = process.env.TRAVELPAYOUTS_TOKEN, private readonly marker = process.env.TRAVELPAYOUTS_MARKER, private readonly fetcher: typeof fetch = fetch) { this.available = Boolean(token); }
  async discover(input: Pick<TravelQuery, 'origins' | 'availabilityStart' | 'availabilityEnd' | 'minDays' | 'maxDays' | 'travellers'>): Promise<FlightItinerary[]> { const key = `round:${JSON.stringify(input)}`, hit = this.cache.get(key); if (hit && hit.expires > Date.now()) return hit.value; const result = (await Promise.all(input.origins.map((origin) => this.fetch(origin, input.availabilityStart.slice(0, 7), false, input.travellers)))).flat(); this.cache.set(key, { expires: Date.now() + 600_000, value: result }); return result; }
  async discoverOneWay(input: FlightSearchRequest): Promise<FlightItinerary[]> { if (input.legs.length !== 1) return []; const leg = input.legs[0], key = `one:${JSON.stringify(input)}`, hit = this.cache.get(key); if (hit && hit.expires > Date.now()) return hit.value; const result = (await Promise.all(leg.origins.flatMap((origin) => leg.destinations.map((destination) => this.fetch(origin, leg.date, true, input.adults, destination))))).flat(); this.cache.set(key, { expires: Date.now() + 600_000, value: result }); return result; }
  private async fetch(origin: string, departureAt: string, oneWay: boolean, adults: number, destination?: string): Promise<FlightItinerary[]> { if (!this.token) throw new Error('Proveedor Aviasales no configurado'); const url = new URL('https://api.travelpayouts.com/aviasales/v3/prices_for_dates'); const params: Record<string, string> = { origin, departure_at: departureAt, one_way: String(oneWay), unique: 'true', sorting: 'price', direct: 'false', currency: 'EUR', limit: '30', page: '1' }; if (destination) params.destination = destination; url.search = new URLSearchParams(params).toString(); const controller = new AbortController(), timer = setTimeout(() => controller.abort(), 8_000); try { const response = await this.fetcher(url, { headers: { 'X-Access-Token': this.token }, signal: controller.signal }); if (response.status === 429) throw new Error('Aviasales ha limitado temporalmente la búsqueda. Inténtalo en un minuto.'); if (!response.ok) throw new Error(`Aviasales no está disponible (${response.status})`); const payload = await response.json() as ApiResponse; if (!payload.success || !Array.isArray(payload.data)) throw new Error(payload.error || 'Respuesta no válida de Aviasales'); return payload.data.map((ticket) => this.normalize(origin, ticket, oneWay, adults)).filter((x): x is FlightItinerary => x !== null); } finally { clearTimeout(timer); } }
  private normalize(fallbackOrigin: string, ticket: ApiTicket, oneWay: boolean, adults: number): FlightItinerary | null { const departure = ticket.departure_at?.slice(0, 10), returned = ticket.return_at?.slice(0, 10), price = ticket.price, origin = ticket.origin_airport || ticket.origin || fallbackOrigin, destination = ticket.destination_airport || ticket.destination; if (!departure || !price || !destination || (!oneWay && !returned)) return null; const legs = oneWay ? [{ origin, destination, departureDate: departure, durationMinutes: ticket.duration, stops: ticket.transfers ?? ticket.number_of_changes }] : [{ origin, destination, departureDate: departure, durationMinutes: ticket.duration, stops: ticket.transfers ?? ticket.number_of_changes }, { origin: destination, destination: origin, departureDate: returned! }]; const timestamp = ticket.found_at || new Date().toISOString(); return { id: `aviasales:${oneWay ? 'ow' : 'rt'}:${origin}:${destination}:${departure}:${returned ?? ''}`, type: oneWay ? 'ONE_WAY' : 'ROUND_TRIP', legs, pricePerPerson: price, groupAmount: price * adults, currency: 'EUR', provider: this.name, retrievedAt: timestamp, status: 'RECENT', confidence: 0.8, ticketType: oneWay ? 'UNKNOWN' : 'SINGLE_TICKET', bookingUrl: ticket.link ? `https://www.aviasales.com/search/${ticket.link}${this.marker ? `?marker=${encodeURIComponent(this.marker)}` : ''}` : undefined }; }
}
