import type { FlightLiveSearchProvider } from '../../../application/providers.js';
import type { FlightItinerary, FlightSearchRequest } from '../../../domain/flight.js';
import { ProviderExecutor, retryProvider } from '../../../application/provider-executor.js';

/** Optional Skyscanner Live Prices boundary. No request is made without a configured API key. */
export class SkyscannerLiveFlightProvider implements FlightLiveSearchProvider {
  readonly name = 'Skyscanner Live'; readonly available: boolean;
  readonly capabilities = { indicative: false, live: true, oneWay: true, roundTrip: true, openJaw: true, multiCity: true, flexibleDates: false, maxLegs: 6 } as const;
  private readonly executor = new ProviderExecutor();
  constructor(private readonly apiKey = process.env.SKYSCANNER_API_KEY, private readonly config = { market: process.env.SKYSCANNER_MARKET ?? 'ES', locale: process.env.SKYSCANNER_LOCALE ?? 'es-ES', currency: process.env.SKYSCANNER_CURRENCY ?? 'EUR' }, private readonly fetcher: typeof fetch = fetch) { this.available = Boolean(apiKey); }
  async search(input: FlightSearchRequest, signal?: AbortSignal): Promise<FlightItinerary[]> { if (!this.apiKey) throw new Error('Skyscanner Live no está configurado'); if (!input.legs.length || input.legs.length > 6 || input.adults < 1 || input.adults > 8) throw new Error('Solicitud de vuelo no válida para Skyscanner'); const key = `skyscanner:${JSON.stringify(input)}`; return this.executor.run(key, async (requestSignal) => { const body = { query: { market: this.config.market, locale: this.config.locale, currency: this.config.currency, adults: input.adults, nearbyAirports: false, queryLegs: input.legs.map((leg) => ({ originPlaceId: { iata: leg.origins[0] }, destinationPlaceId: { iata: leg.destinations[0] }, date: date(leg.date) })) } }; const create = await retryProvider(() => this.request('https://partners.api.skyscanner.net/apiservices/v3/flights/live/search/create', body, requestSignal)); const token = String(create.sessionToken ?? ''); if (!token) throw new Error('Respuesta inválida de Skyscanner'); let payload = create; for (let i = 0; i < 4 && String(payload.status ?? payload.content?.status ?? '').toUpperCase() !== 'RESULT_STATUS_COMPLETE'; i++) payload = await retryProvider(() => this.request(`https://partners.api.skyscanner.net/apiservices/v3/flights/live/search/poll/${encodeURIComponent(token)}`, {}, requestSignal)); return normalize(payload, input, this.name); }, signal); }
  private async request(url: string, body: unknown, signal: AbortSignal): Promise<any> { const response = await this.fetcher(url, { method: 'POST', headers: { 'x-api-key': this.apiKey!, 'content-type': 'application/json' }, body: JSON.stringify(body), signal }); if (response.status === 429) throw new Error('Skyscanner 429'); if (!response.ok) throw new Error(`Skyscanner ${response.status}`); return response.json(); }
}
const date = (value: string) => { const [year, month, day] = value.split('-').map(Number); return { year, month, day }; };
function normalize(payload: any, input: FlightSearchRequest, provider: string): FlightItinerary[] { const content = payload.content ?? payload, itineraries = content.itineraries ?? []; return itineraries.map((item: any, index: number) => { const price = Number(item.pricingOptions?.[0]?.price?.amount ?? item.price?.amount); if (!Number.isFinite(price)) return undefined; const legs = (item.legs ?? input.legs).map((leg: any, i: number) => ({ origin: leg.origin?.iata ?? input.legs[i].origins[0], destination: leg.destination?.iata ?? input.legs[i].destinations[0], departureDate: input.legs[i].date, departureDateTime: leg.departureDateTime, arrivalDateTime: leg.arrivalDateTime, durationMinutes: leg.durationInMinutes, stops: leg.stopCount })); return { id: `skyscanner:${item.id ?? index}`, type: legs.length === 1 ? 'ONE_WAY' : legs.length === 2 && legs[0].origin === legs[1].destination && legs[0].destination === legs[1].origin ? 'ROUND_TRIP' : legs.length === 2 ? 'OPEN_JAW' : 'MULTI_CITY', legs, pricePerPerson: price, groupAmount: price * input.adults, currency: 'EUR', provider, status: 'LIVE', confidence: 0.95, retrievedAt: new Date().toISOString(), bookingUrl: item.deepLink, ticketType: 'UNKNOWN' } as FlightItinerary; }).filter((item: FlightItinerary | undefined): item is FlightItinerary => Boolean(item)); }
