import type { TripCandidate, TravelQuery } from '../domain/travel-query.js';
import { itineraryDates, itineraryKey, type FlightItinerary } from '../domain/flight.js';
import type { AccommodationProvider, CarRentalProvider, FlightProvider, RoutingProvider } from './providers.js';
import { ProviderExecutor } from './provider-executor.js'; import { RoadtripOpportunityEngine } from './roadtrip-opportunity-engine.js'; import { FlightCompositionEngine } from './flight-composition-engine.js'; import { AirportAccessService } from './airport-access-service.js';
import { generateDateCombinations } from './date-engine.js'; import { DestinationService } from '../infrastructure/destination/destination-service.js';
export interface ProviderMeta { name: string; type: 'flight-discovery' | 'flight-live' | 'accommodation' | 'car' | 'routing'; status: 'AVAILABLE' | 'UNAVAILABLE' | 'FAILED'; dataStatus?: 'LIVE' | 'RECENT'; capabilities?: import('../domain/flight.js').FlightProviderCapabilities; }
export interface DiscoveryResult { data: TripCandidate[]; meta: { providers: ProviderMeta[]; generatedAt: string; warnings: string[]; }; }
const unavailable = (provider: string) => ({ currency: 'EUR' as const, status: 'UNAVAILABLE' as const, provider });
const quality = (flight: FlightItinerary) => flight.legs.reduce((total, leg) => total + (leg.stops ?? 0), 0);
function rank(candidate: TripCandidate, query: TravelQuery): TripCandidate { let score = 42; const rationale: string[] = []; const price = candidate.cost.knownPerPerson ?? candidate.flight.pricePerPerson; score += Math.max(0, 30 - price / 20); rationale.push(`€${Math.round(price)}/persona de coste conocido`); if (quality(candidate.flight) === 0) { score += 12; rationale.push('Vuelo directo'); } if (candidate.flight.type === 'OPEN_JAW') rationale.push('Open jaw: evita volver al aeropuerto de llegada'); if (candidate.roadtrip) score -= candidate.roadtrip.route.durationMinutes / 180; if (candidate.dates.nights >= query.minDays) score += 7; if (candidate.hotel?.reviewScore) score += Math.min(10, candidate.hotel.reviewScore); return { ...candidate, score: Math.min(100, Math.round(score)), rationale: [...candidate.rationale, ...rationale] }; }
function toCandidate(flight: FlightItinerary, query: TravelQuery, destinations: DestinationService, accommodationProvider: AccommodationProvider): TripCandidate | undefined { const dates = itineraryDates(flight), arrival = flight.legs[0]; if (!dates || !arrival) return undefined; const destination = destinations.resolve(arrival.destination); return { id: `trip:${flight.id}`, destination, origin: arrival.origin, dates, travellers: query.travellers, rooms: query.rooms, type: 'CITY', title: destination.city, flight, stops: quality(flight), cost: { flights: { amountPerPerson: flight.pricePerPerson, groupAmount: flight.groupAmount, currency: 'EUR', status: flight.status, provider: flight.provider, retrievedAt: flight.retrievedAt }, accommodation: unavailable(accommodationProvider.name), transport: unavailable('No calculado'), access: unavailable('Acceso a aeropuerto pendiente'), knownTotal: flight.groupAmount, knownPerPerson: flight.pricePerPerson, currency: 'EUR' }, score: 0, rationale: [], provider: flight.provider, retrievedAt: flight.retrievedAt, status: flight.status, confidence: flight.confidence, bookingLinks: flight.bookingUrl ? [{ label: 'Ver vuelo', url: flight.bookingUrl, provider: flight.provider }] : [] }; }
export async function discoverTrips(query: TravelQuery, flightProvider: FlightProvider, accommodationProvider: AccommodationProvider, destinations = new DestinationService(), routing?: RoutingProvider, cars?: CarRentalProvider): Promise<DiscoveryResult> {
  const warnings: string[] = [], providers: ProviderMeta[] = [{ name: flightProvider.name, type: 'flight-discovery', status: flightProvider.available ? 'AVAILABLE' : 'UNAVAILABLE', dataStatus: 'RECENT', capabilities: flightProvider.capabilities }, { name: accommodationProvider.name, type: 'accommodation', status: accommodationProvider.available ? 'AVAILABLE' : 'UNAVAILABLE' }];
  if (!flightProvider.available) return { data: [], meta: { providers, generatedAt: new Date().toISOString(), warnings: ['El proveedor de vuelos no está configurado.'] } };
  const validDates = new Set(generateDateCombinations(query.availabilityStart, query.availabilityEnd, query.minDays, query.maxDays).map((d) => `${d.departureDate}:${d.returnDate}`));
  let itineraries: FlightItinerary[]; try { itineraries = await flightProvider.discover(query); } catch (error) { providers[0].status = 'FAILED'; return { data: [], meta: { providers, generatedAt: new Date().toISOString(), warnings: [error instanceof Error ? error.message : 'No se pudo consultar vuelos.'] } }; }
  const unique = new Map<string, FlightItinerary>(); for (const flight of itineraries) { const dates = itineraryDates(flight); if (!dates || !validDates.has(`${dates.departureDate}:${dates.returnDate}`) || (query.budgetPerPerson && flight.pricePerPerson > query.budgetPerPerson)) continue; const key = itineraryKey(flight), old = unique.get(key); if (!old || flight.pricePerPerson < old.pricePerPerson) unique.set(key, flight); }
  const candidates = [...unique.values()].slice(0, Number(process.env.MAX_ACCOMMODATION_ENRICHMENTS ?? 10)).map((flight) => toCandidate(flight, query, destinations, accommodationProvider)).filter((x): x is TripCandidate => Boolean(x));
  if (!accommodationProvider.available) warnings.push('Alojamiento no disponible desde un proveedor en directo.'); else { const pool = new ProviderExecutor(); await Promise.all(candidates.map((candidate) => pool.run(`accommodation:${candidate.id}`, async () => { try { const hotel = (await accommodationProvider.search({ destination: candidate.destination, checkin: candidate.dates.departureDate, checkout: candidate.dates.returnDate, adults: query.travellers, rooms: query.rooms, bookerCountry: 'ES' }))[0]; if (!hotel?.totalStayPrice) return; candidate.hotel = { ...hotel, status: 'LIVE' }; candidate.cost.accommodation = { groupAmount: hotel.totalStayPrice, currency: 'EUR', status: 'LIVE', provider: hotel.provider, retrievedAt: hotel.retrievedAt }; candidate.cost.knownTotal = (candidate.cost.flights.groupAmount ?? 0) + hotel.totalStayPrice; candidate.cost.knownPerPerson = candidate.cost.knownTotal / query.travellers; if (hotel.bookingUrl) candidate.bookingLinks.push({ label: 'Ver estancia', url: hotel.bookingUrl, provider: hotel.provider }); } catch { providers[1].status = 'FAILED'; warnings.push('No se pudo obtener alojamiento para algunos destinos.'); } }))); }
  const ranked = candidates.map((candidate) => rank(candidate, query));
  if (routing && cars) { providers.push({ name: routing.name, type: 'routing', status: routing.available ? 'AVAILABLE' : 'UNAVAILABLE' }, { name: cars.name, type: 'car', status: cars.available ? 'AVAILABLE' : 'UNAVAILABLE' }); const roads = new RoadtripOpportunityEngine((d, max) => destinations.nearby(d, max), routing, cars); for (const city of [...ranked].slice(0, Number(process.env.MAX_ROADTRIP_ENRICHMENTS ?? 5))) { const output = await roads.create(city, query); if (output.warning) warnings.push(output.warning); for (const plan of output.plans) { const carPart = plan.car?.groupAmount === undefined ? unavailable(cars.name) : { groupAmount: plan.car.groupAmount, currency: 'EUR' as const, status: plan.car.status, provider: plan.car.provider, retrievedAt: plan.car.retrievedAt, note: plan.car.oneWayFee ? `Incluye ${plan.car.oneWayFee}€ de tasa one-way` : undefined }; const total = (city.cost.knownTotal ?? 0) + (plan.car?.groupAmount ?? 0) + (plan.fuel.groupAmount ?? 0); ranked.push(rank({ ...city, id: plan.id, type: 'ROADTRIP', title: plan.stops.map((x) => x.destination.city).join(' → '), roadtrip: plan, cost: { ...city.cost, transport: carPart, knownTotal: total, knownPerPerson: total / query.travellers }, score: 0, rationale: [...plan.rationale], bookingLinks: [...city.bookingLinks, ...(plan.car?.bookingUrl ? [{ label: 'Ver coche', url: plan.car.bookingUrl, provider: plan.car.provider }] : [])] }, query)); } } }
  if (query.flightPreference?.allowOpenJaw !== false && flightProvider.discoverOneWay && routing && cars) await enrichOpenJaws(ranked, query, flightProvider, destinations, accommodationProvider, warnings);
  const data = ranked.sort((a, b) => b.score - a.score || (a.cost.knownPerPerson ?? Infinity) - (b.cost.knownPerPerson ?? Infinity)); if (!data.length) warnings.push('No se encontraron vuelos compatibles.'); if (data.some((item) => item.flight.status === 'RECENT')) warnings.push('Precio reciente; confirma precio antes de reservar.'); return { data, meta: { providers, generatedAt: new Date().toISOString(), warnings: [...new Set(warnings)] } };
}
async function enrichOpenJaws(ranked: TripCandidate[], query: TravelQuery, provider: FlightProvider, destinations: DestinationService, accommodation: AccommodationProvider, warnings: string[]) { const access = new AirportAccessService(() => destinations.airports()), composer = new FlightCompositionEngine(); for (const roadtrip of ranked.filter((trip) => trip.type === 'ROADTRIP').slice(0, Number(process.env.MAX_ROADTRIP_ENRICHMENTS ?? 5))) { const exits = access.nearby(roadtrip.roadtrip!.end); for (const exit of exits) try { const outbound = await provider.discoverOneWay!({ adults: query.travellers, legs: [{ origins: [roadtrip.origin], destinations: [roadtrip.destination.airportCode], date: roadtrip.dates.departureDate }] }); const inbound = await provider.discoverOneWay!({ adults: query.travellers, legs: [{ origins: [exit.airport.airportCode], destinations: [roadtrip.origin], date: roadtrip.dates.returnDate }] }); for (const flight of composer.composeOpenJaws(outbound, inbound, query.travellers)) { const variant = toCandidate(flight, query, destinations, accommodation); if (!variant) continue; const extra = exit.durationMinutes ?? 0; ranked.push(rank({ ...variant, id: `${roadtrip.id}:${flight.id}`, type: 'ROADTRIP', title: roadtrip.title, roadtrip: { ...roadtrip.roadtrip!, car: roadtrip.roadtrip!.car ? { ...roadtrip.roadtrip!.car, dropoff: exit.airport.airportCode } : undefined }, cost: { ...roadtrip.cost, flights: { amountPerPerson: flight.pricePerPerson, groupAmount: flight.groupAmount, currency: 'EUR', status: flight.status, provider: flight.provider, retrievedAt: flight.retrievedAt }, knownTotal: (roadtrip.cost.knownTotal ?? 0) - (roadtrip.flight.groupAmount) + flight.groupAmount, knownPerPerson: ((roadtrip.cost.knownTotal ?? 0) - roadtrip.flight.groupAmount + flight.groupAmount) / query.travellers, access: { groupAmount: undefined, currency: 'EUR', status: 'ESTIMATED', provider: exit.provider, note: `~${extra} min hasta ${exit.airport.airportCode}; coste de acceso desconocido` } }, rationale: [...roadtrip.rationale, `Salida desde ${exit.airport.airportCode}: ~${extra} min de acceso; tasa one-way del coche pendiente`], bookingLinks: variant.bookingLinks }, query)); } } catch { warnings.push('No se pudieron estimar algunos retornos open-jaw.'); } } }
export function parseTravelQuery(input: Partial<TravelQuery>): TravelQuery { const legacy = input.origin?.trim().toUpperCase(); const origins = (input.origins?.length ? input.origins : legacy ? [legacy] : ['VGO']).map((x) => x.trim().toUpperCase()).filter((x) => /^[A-Z]{3}$/.test(x)); const query = { mode: 'DISCOVER' as const, travellers: 1, rooms: 1, car: 'IF_WORTH_IT' as const, minDays: 2, maxDays: 6, flightPreference: { allowOpenJaw: true, allowMultiCity: false }, ...input, origins } as TravelQuery; if (!query.availabilityStart || !query.availabilityEnd) throw new Error('availabilityStart y availabilityEnd son obligatorias'); if (!origins.length) throw new Error('Añade al menos un aeropuerto IATA válido'); if (query.travellers < 1 || query.travellers > 12 || query.rooms < 1 || query.rooms > query.travellers) throw new Error('Viajeros y habitaciones no son válidos'); if (query.minDays < 1 || query.maxDays < query.minDays) throw new Error('El rango de noches no es válido'); return query; }
