import type { TravelQuery, TripCandidate } from '../domain/travel-query.js';
import type { FlightProvider, FlightQuote } from './providers.js';
import { generateDateCombinations } from './date-engine.js';
export interface DiscoveryResult { data: TripCandidate[]; meta: { providers: string[]; realResults: boolean; generatedAt: string; warnings: string[]; }; }
function rank(q: FlightQuote, query: TravelQuery) { let score = Math.max(10, 65 - Math.min(35, q.price / 8)); const rationale: string[] = []; if ((q.stops ?? 0) === 0) { score += 12; rationale.push('Vuelo directo'); } if (q.dates.nights >= query.minDays) { score += 7; rationale.push(`${q.dates.nights} noches disponibles`); } if (q.source.status === 'RECENT') { score += 7; rationale.push('Precio reciente de Aviasales'); } if (query.budgetPerPerson && q.price <= query.budgetPerPerson) { score += 10; rationale.push('Dentro de tu presupuesto de vuelo'); } if (q.price < 150) rationale.unshift('Una de las opciones más económicas para tus fechas'); return { score: Math.min(100, Math.round(score)), rationale: rationale.length ? rationale : ['Opción compatible con tu ventana de viaje'] }; }
export async function discoverTrips(query: TravelQuery, provider: FlightProvider): Promise<DiscoveryResult> {
  if (!provider.available) return { data: [], meta: { providers: [provider.name], realResults: false, generatedAt: new Date().toISOString(), warnings: ['El proveedor Aviasales no está configurado. Añade TRAVELPAYOUTS_TOKEN para buscar precios recientes.'] } };
  const validDates = new Set(generateDateCombinations(query.availabilityStart, query.availabilityEnd, query.minDays, query.maxDays).map((d) => `${d.departureDate}:${d.returnDate}`));
  try { const unique = new Map<string, FlightQuote>(); for (const quote of await provider.discover(query)) { if (!validDates.has(`${quote.dates.departureDate}:${quote.dates.returnDate}`) || (query.budgetPerPerson && quote.price > query.budgetPerPerson)) continue; const key = `${quote.origin}:${quote.destinationCode}:${quote.dates.departureDate}:${quote.dates.returnDate}`; if (!unique.has(key) || unique.get(key)!.price > quote.price) unique.set(key, quote); }
    const data = [...unique.values()].map((q) => { const ranked = rank(q, query), lodging = 70 * q.dates.nights; return { id: `${q.origin}-${q.destinationCode}-${q.dates.departureDate}`, destination: q.destination, destinationCode: q.destinationCode, country: q.country, origin: q.origin, dates: q.dates, type: 'CITY', title: q.destination, stops: q.stops, cost: { flights: { amount: q.price, status: q.source.status, provider: q.source.provider }, accommodation: { amount: lodging, status: 'ESTIMATED', provider: 'BotPlanner heuristic', note: 'Estimación sin proveedor de alojamiento' }, transport: { status: 'UNAVAILABLE', provider: 'No calculado' }, access: { status: 'UNAVAILABLE', provider: 'No calculado' }, knownTotal: q.price, estimatedTotal: q.price + lodging, currency: 'EUR' }, score: ranked.score, rationale: ranked.rationale, provider: q.source.provider, retrievedAt: q.source.retrievedAt, status: q.source.status, confidence: q.source.confidence, bookingLinks: q.bookingLink ? [q.bookingLink] : [] } satisfies TripCandidate; }).sort((a,b) => b.score - a.score || a.cost.knownTotal - b.cost.knownTotal);
    return { data, meta: { providers: [provider.name], realResults: data.some((d) => d.status === 'RECENT' || d.status === 'LIVE'), generatedAt: new Date().toISOString(), warnings: data.length ? ['Los precios de Aviasales son observaciones recientes en caché, no precios LIVE de reserva.'] : ['No se encontraron vuelos compatibles.'] } };
  } catch (e) { return { data: [], meta: { providers: [provider.name], realResults: false, generatedAt: new Date().toISOString(), warnings: [e instanceof Error ? e.message : 'No se pudo consultar el proveedor.'] } }; }
}
export function parseTravelQuery(input: Partial<TravelQuery>): TravelQuery { const legacy = input.origin?.trim().toUpperCase(); const origins = (input.origins?.length ? input.origins : legacy ? [legacy] : ['VGO']).map((x) => x.trim().toUpperCase()).filter((x) => /^[A-Z]{3}$/.test(x)); const query = { mode: 'DISCOVER' as const, travellers: 1, car: 'IF_WORTH_IT' as const, minDays: 2, maxDays: 6, ...input, origins } as TravelQuery; if (!query.availabilityStart || !query.availabilityEnd) throw new Error('availabilityStart y availabilityEnd son obligatorias'); if (!origins.length) throw new Error('Añade al menos un aeropuerto IATA válido'); if (query.travellers < 1 || query.travellers > 12) throw new Error('travellers debe estar entre 1 y 12'); if (query.minDays < 1 || query.maxDays < query.minDays) throw new Error('El rango de noches no es válido'); return query; }
