import type { TripCandidate, TravelQuery } from '../domain/travel-query.js';
import type { AccommodationProvider, CarRentalProvider, FlightProvider, FlightQuote, RoutingProvider } from './providers.js'; import { ProviderExecutor } from './provider-executor.js'; import { RoadtripOpportunityEngine } from './roadtrip-opportunity-engine.js';
import { generateDateCombinations } from './date-engine.js';
import { DestinationService } from '../infrastructure/destination/destination-service.js';
export interface ProviderMeta { name: string; type: 'flight' | 'accommodation' | 'car' | 'routing'; status: 'AVAILABLE' | 'UNAVAILABLE' | 'FAILED'; }
export interface DiscoveryResult { data: TripCandidate[]; meta: { providers: ProviderMeta[]; generatedAt: string; warnings: string[]; }; }
const unavailable = (provider: string) => ({ currency: 'EUR' as const, status: 'UNAVAILABLE' as const, provider });
function rank(candidate: TripCandidate, query: TravelQuery): TripCandidate { let score = 42; const rationale: string[] = []; const flight = candidate.cost.flights.amountPerPerson!; if (candidate.cost.knownPerPerson) { score += Math.max(0, 30 - candidate.cost.knownPerPerson / 20); rationale.push(`€${Math.round(candidate.cost.knownPerPerson)}/persona de vuelo + alojamiento`); } else rationale.push(`€${Math.round(flight)}/persona de vuelo; alojamiento pendiente`); if ((candidate.stops ?? 0) === 0) { score += 12; rationale.push('Vuelo directo'); } if (candidate.dates.nights >= query.minDays) { score += 7; rationale.push(`${candidate.dates.nights} noches`); } if (candidate.hotel?.reviewScore) { score += Math.min(10, candidate.hotel.reviewScore); rationale.push(`Alojamiento valorado con ${candidate.hotel.reviewScore}`); } if (candidate.cost.flights.status === 'RECENT' && candidate.cost.accommodation.status === 'LIVE') rationale.push('Precios de vuelo y alojamiento respaldados por proveedores'); return { ...candidate, score: Math.min(100, Math.round(score)), rationale }; }
export async function discoverTrips(query: TravelQuery, flightProvider: FlightProvider, accommodationProvider: AccommodationProvider, destinations = new DestinationService(), routing?: RoutingProvider, cars?: CarRentalProvider): Promise<DiscoveryResult> {
  const warnings: string[] = [], providers: ProviderMeta[] = [{ name: flightProvider.name, type: 'flight', status: flightProvider.available ? 'AVAILABLE' : 'UNAVAILABLE' }, { name: accommodationProvider.name, type: 'accommodation', status: accommodationProvider.available ? 'AVAILABLE' : 'UNAVAILABLE' }];
  if (!flightProvider.available) return { data: [], meta: { providers, generatedAt: new Date().toISOString(), warnings: ['El proveedor de vuelos no está configurado.'] } };
  const validDates = new Set(generateDateCombinations(query.availabilityStart, query.availabilityEnd, query.minDays, query.maxDays).map((d) => `${d.departureDate}:${d.returnDate}`));
  let quotes: FlightQuote[]; try { quotes = await flightProvider.discover(query); } catch (error) { providers[0].status = 'FAILED'; return { data: [], meta: { providers, generatedAt: new Date().toISOString(), warnings: [error instanceof Error ? error.message : 'No se pudo consultar vuelos.'] } }; }
  const unique = new Map<string, FlightQuote>(); for (const quote of quotes) { if (!validDates.has(`${quote.dates.departureDate}:${quote.dates.returnDate}`) || (query.budgetPerPerson && quote.pricePerPerson > query.budgetPerPerson)) continue; const key = `${quote.origin}:${quote.destinationCode}:${quote.dates.departureDate}:${quote.dates.returnDate}`; if (!unique.has(key) || unique.get(key)!.pricePerPerson > quote.pricePerPerson) unique.set(key, quote); }
  const candidates = [...unique.values()].slice(0, Number(process.env.MAX_ACCOMMODATION_ENRICHMENTS ?? 10)).map((quote): TripCandidate => { const destination = destinations.resolve(quote.destinationCode), flightGroup = quote.pricePerPerson * query.travellers; return { id: `${quote.origin}-${quote.destinationCode}-${quote.dates.departureDate}`, destination, origin: quote.origin, dates: quote.dates, travellers: query.travellers, rooms: query.rooms, type: 'CITY', title: destination.city, stops: quote.stops, cost: { flights: { amountPerPerson: quote.pricePerPerson, groupAmount: flightGroup, currency: 'EUR', status: quote.source.status, provider: quote.source.provider, retrievedAt: quote.source.retrievedAt }, accommodation: unavailable(accommodationProvider.name), transport: unavailable('No calculado'), access: unavailable('No calculado'), knownTotal: flightGroup, knownPerPerson: quote.pricePerPerson, currency: 'EUR' }, score: 0, rationale: [], provider: quote.source.provider, retrievedAt: quote.source.retrievedAt, status: quote.source.status, confidence: quote.source.confidence, bookingLinks: quote.bookingLink ? [{ label: 'Ver vuelo', url: quote.bookingLink, provider: quote.source.provider }] : [] }; });
  if (!accommodationProvider.available) warnings.push('Alojamiento no disponible desde un proveedor en directo.'); else { const pool=new ProviderExecutor(); await Promise.all(candidates.map(candidate=>pool.run(`accommodation:${candidate.id}`,async()=>{try { const hotel=(await accommodationProvider.search({destination:candidate.destination,checkin:candidate.dates.departureDate,checkout:candidate.dates.returnDate,adults:query.travellers,rooms:query.rooms,bookerCountry:'ES'}))[0];if(!hotel?.totalStayPrice)return;candidate.hotel={...hotel,status:'LIVE'};candidate.cost.accommodation={groupAmount:hotel.totalStayPrice,currency:'EUR',status:'LIVE',provider:hotel.provider,retrievedAt:hotel.retrievedAt};candidate.cost.knownTotal=(candidate.cost.flights.groupAmount??0)+hotel.totalStayPrice;candidate.cost.knownPerPerson=candidate.cost.knownTotal/query.travellers;if(hotel.bookingUrl)candidate.bookingLinks.push({label:'Ver estancia',url:hotel.bookingUrl,provider:hotel.provider});}catch{providers[1].status='FAILED';warnings.push('No se pudo obtener alojamiento para algunos destinos.');}}))); }
  const ranked=candidates.map(candidate=>rank(candidate,query)); if(routing&&cars){providers.push({name:routing.name,type:'routing',status:routing.available?'AVAILABLE':'UNAVAILABLE'},{name:cars.name,type:'car',status:cars.available?'AVAILABLE':'UNAVAILABLE'});const engine=new RoadtripOpportunityEngine((d,max)=>destinations.nearby(d,max),routing,cars);for(const city of ranked.slice(0,Number(process.env.MAX_ROADTRIP_ENRICHMENTS??5))){const output=await engine.create(city,query);if(output.warning)warnings.push(output.warning);for(const plan of output.plans){const carPart=plan.car?.groupAmount===undefined?unavailable(cars.name):{groupAmount:plan.car.groupAmount,currency:'EUR' as const,status:plan.car.status,provider:plan.car.provider,retrievedAt:plan.car.retrievedAt,note:plan.car.oneWayFee?`Incluye ${plan.car.oneWayFee}€ de tasa one-way`:undefined};const total=(city.cost.knownTotal??0)+(plan.car?.groupAmount??0)+(plan.fuel.groupAmount??0);ranked.push({...city,id:plan.id,type:'ROADTRIP',title:plan.stops.map(x=>x.destination.city).join(' → '),roadtrip:plan,cost:{...city.cost,transport:carPart,knownTotal:total,knownPerPerson:total/query.travellers},score:plan.score,rationale:[...plan.rationale,...city.rationale],bookingLinks:[...city.bookingLinks,...(plan.car?.bookingUrl?[{label:'Ver coche',url:plan.car.bookingUrl,provider:plan.car.provider}]:[])]});}}}
  const data=ranked.sort((a,b)=>b.score-a.score||(a.cost.knownPerPerson??Infinity)-(b.cost.knownPerPerson??Infinity));if(!data.length)warnings.push('No se encontraron vuelos compatibles.');if(data.some(item=>item.cost.flights.status==='RECENT'))warnings.push('Los vuelos de Aviasales son precios recientes, no precios LIVE de reserva.');return{data,meta:{providers,generatedAt:new Date().toISOString(),warnings:[...new Set(warnings)]}};
}
export function parseTravelQuery(input: Partial<TravelQuery>): TravelQuery { const legacy = input.origin?.trim().toUpperCase(); const origins = (input.origins?.length ? input.origins : legacy ? [legacy] : ['VGO']).map((x) => x.trim().toUpperCase()).filter((x) => /^[A-Z]{3}$/.test(x)); const query = { mode: 'DISCOVER' as const, travellers: 1, rooms: 1, car: 'IF_WORTH_IT' as const, minDays: 2, maxDays: 6, ...input, origins } as TravelQuery; if (!query.availabilityStart || !query.availabilityEnd) throw new Error('availabilityStart y availabilityEnd son obligatorias'); if (!origins.length) throw new Error('Añade al menos un aeropuerto IATA válido'); if (query.travellers < 1 || query.travellers > 12 || query.rooms < 1 || query.rooms > query.travellers) throw new Error('Viajeros y habitaciones no son válidos'); if (query.minDays < 1 || query.maxDays < query.minDays) throw new Error('El rango de noches no es válido'); return query; }
