import { createReadStream } from 'node:fs'; import { stat } from 'node:fs/promises'; import { createServer } from 'node:http'; import { extname, join } from 'node:path';
import { generateDateCombinations } from './application/date-engine.js'; import { discoverTrips, parseTravelQuery } from './application/discovery-engine.js'; import { AviasalesFlightProvider } from './infrastructure/providers/aviasales/aviasales-flight-provider.js';
const publicDir = join(process.cwd(), 'public'), provider = new AviasalesFlightProvider(), types: Record<string,string> = { '.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8' };
const server = createServer((req, res) => { res.setHeader('Access-Control-Allow-Origin','*'); if (req.method === 'OPTIONS') { res.writeHead(204,{'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'content-type'}).end(); return; }
  if (req.method === 'GET' && req.url === '/health') { res.writeHead(200,{'Content-Type':'application/json'}).end(JSON.stringify({ok:true,service:'botplanner',providerAvailable:provider.available})); return; }
  if (req.method === 'GET' && req.url?.startsWith('/api/date-combinations')) { const u=new URL(req.url,'http://localhost'); try { res.writeHead(200,{'Content-Type':'application/json'}).end(JSON.stringify({data:generateDateCombinations(u.searchParams.get('start')??'',u.searchParams.get('end')??'',Number(u.searchParams.get('minDays')??1),Number(u.searchParams.get('maxDays')??1))})); } catch(e) { res.writeHead(400,{'Content-Type':'application/json'}).end(JSON.stringify({error:e instanceof Error?e.message:'Invalid request'})); } return; }
  if (req.method === 'POST' && req.url === '/api/discover') { let body=''; req.on('data',(chunk) => { body += chunk; if(body.length>100000) req.destroy(); }); req.on('end',async () => { try { const result=await discoverTrips(parseTravelQuery(JSON.parse(body)),provider); res.writeHead(200,{'Content-Type':'application/json'}).end(JSON.stringify(result)); } catch(e) { res.writeHead(400,{'Content-Type':'application/json'}).end(JSON.stringify({error:e instanceof Error?e.message:'Invalid request'})); } }); return; }
  if (req.method === 'GET') { const target=req.url==='/'?'index.html':req.url?.slice(1)??'', file=join(publicDir,target); if(!file.startsWith(publicDir)){res.writeHead(403).end();return;} stat(file).then(()=>{res.writeHead(200,{'Content-Type':types[extname(file)]??'application/octet-stream'});createReadStream(file).pipe(res);}).catch(()=>res.writeHead(404,{'Content-Type':'application/json'}).end(JSON.stringify({error:'Not found'}))); return; }
  res.writeHead(404,{'Content-Type':'application/json'}).end(JSON.stringify({error:'Not found'}));
}); server.listen(Number(process.env.PORT??4100),()=>console.log(`Botplanner listening on http://localhost:${process.env.PORT??4100}`));
