import { createReadStream } from 'node:fs'; import { stat } from 'node:fs/promises'; import { createServer } from 'node:http'; import { extname, join } from 'node:path';
import { generateDateCombinations } from './application/date-engine.js'; import { discoverTrips, parseTravelQuery } from './application/discovery-engine.js'; import { DiscoveryJobService } from './application/discovery-jobs.js'; import { AviasalesFlightProvider } from './infrastructure/providers/aviasales/aviasales-flight-provider.js'; import { BookingComAccommodationProvider } from './infrastructure/providers/booking/booking-com-accommodation-provider.js'; import { BookingComCarRentalProvider } from './infrastructure/providers/booking/booking-com-car-rental-provider.js'; import { OpenRouteServiceRoutingProvider } from './infrastructure/providers/routing/open-route-service-routing-provider.js'; import { DestinationService } from './infrastructure/destination/destination-service.js';
const publicDir = join(process.cwd(), 'public'), flightProvider = new AviasalesFlightProvider(), accommodationProvider = new BookingComAccommodationProvider(), carProvider=new BookingComCarRentalProvider(), routingProvider=new OpenRouteServiceRoutingProvider(), destinations = new DestinationService(), jobs = new DiscoveryJobService(flightProvider, accommodationProvider, destinations,15*60*1000,routingProvider,carProvider), types: Record<string,string> = { '.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8' };
const json = (res: import('node:http').ServerResponse, status: number, value: unknown) => res.writeHead(status, {'Content-Type':'application/json'}).end(JSON.stringify(value));
const readBody = (req: import('node:http').IncomingMessage) => new Promise<string>((resolve, reject) => { let body=''; req.on('data',(chunk) => { body += chunk; if(body.length>100000) { reject(new Error('Request demasiado grande')); req.destroy(); } }); req.on('end',()=>resolve(body)); req.on('error', reject); });
const server = createServer((req, res) => { res.setHeader('Access-Control-Allow-Origin','*'); if (req.method === 'OPTIONS') { res.writeHead(204,{'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'content-type'}).end(); return; }
  if (req.method === 'GET' && req.url === '/health') { res.writeHead(200,{'Content-Type':'application/json'}).end(JSON.stringify({ok:true,service:'botplanner',providers:{flight:flightProvider.available,accommodation:accommodationProvider.available,car:carProvider.available,routing:routingProvider.available}})); return; }
  if (req.method === 'GET' && req.url?.startsWith('/api/airports')) { const u=new URL(req.url,'http://localhost'); res.writeHead(200,{'Content-Type':'application/json'}).end(JSON.stringify({data:destinations.search(u.searchParams.get('q')??'')})); return; }
  if (req.method === 'GET' && req.url?.startsWith('/api/date-combinations')) { const u=new URL(req.url,'http://localhost'); try { res.writeHead(200,{'Content-Type':'application/json'}).end(JSON.stringify({data:generateDateCombinations(u.searchParams.get('start')??'',u.searchParams.get('end')??'',Number(u.searchParams.get('minDays')??1),Number(u.searchParams.get('maxDays')??1))})); } catch(e) { res.writeHead(400,{'Content-Type':'application/json'}).end(JSON.stringify({error:e instanceof Error?e.message:'Invalid request'})); } return; }
  if (req.method === 'POST' && req.url === '/api/discovery-jobs') { readBody(req).then((body)=>json(res,202,{data:jobs.create(JSON.parse(body))})).catch((e)=>json(res,400,{error:e instanceof Error?e.message:'Solicitud no válida'})); return; }
  const jobPath = req.url?.match(/^\/api\/discovery-jobs\/([^/]+)(?:\/(events))?$/); if (jobPath) { const job = jobs.get(jobPath[1]); if (!job) { json(res,404,{error:'Búsqueda no encontrada o caducada'}); return; } if (jobPath[2] === 'events' && req.method === 'GET') { res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'}); const send=(event: unknown)=>res.write(`data: ${JSON.stringify(event)}\n\n`); job.events.forEach(send); const unsubscribe=jobs.subscribe(job.id,send); req.on('close',unsubscribe); return; } if (req.method === 'GET') { json(res,200,{data:job}); return; } if (req.method === 'PATCH') { readBody(req).then((body)=>{ const updated=jobs.refine(job.id,JSON.parse(body)); return updated ? json(res,202,{data:updated}) : json(res,404,{error:'Búsqueda no encontrada'}); }).catch((e)=>json(res,400,{error:e instanceof Error?e.message:'Solicitud no válida'})); return; } }
  const refreshPath = req.url?.match(/^\/api\/trips\/([^/]+)\/refresh$/); if (refreshPath && req.method === 'POST') { jobs.refresh(decodeURIComponent(refreshPath[1])).then((result)=>result?json(res,200,{data:result}):json(res,404,{error:'Viaje no encontrado o caducado'})); return; }
  if (req.method === 'POST' && req.url === '/api/discover') { readBody(req).then(async(body)=>json(res,200,await discoverTrips(parseTravelQuery(JSON.parse(body)),flightProvider,accommodationProvider,destinations,routingProvider,carProvider))).catch((e)=>json(res,400,{error:e instanceof Error?e.message:'Solicitud no válida'})); return; }
  if (req.method === 'GET') { const target=req.url==='/'?'dist/index.html':req.url?.slice(1)??'', file=join(publicDir,target); if(!file.startsWith(publicDir)){res.writeHead(403).end();return;} stat(file).then(()=>{res.writeHead(200,{'Content-Type':types[extname(file)]??'application/octet-stream'});createReadStream(file).pipe(res);}).catch(()=>res.writeHead(404,{'Content-Type':'application/json'}).end(JSON.stringify({error:'Run npm run build to create the frontend'}))); return; }
  res.writeHead(404,{'Content-Type':'application/json'}).end(JSON.stringify({error:'Not found'}));
}); server.listen(Number(process.env.PORT??4100),()=>console.log(`Botplanner listening on http://localhost:${process.env.PORT??4100}`));
